### ISSUE TITLE
AWS EMR instance, Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by amuzychka** [blink1073/tifffile#36]
Hello,
tifffile==0.13.4 failed during pip install with message:
Command "python setup.py egg_info" failed with error code 1 in /mnt/tmp/pip-build-NmIUNG/tifffile/

With 0.12.x all work fine.

**Comment by blink1073** [comment]
Hi @amuzychka, what OS and python version?  What was the exact command you used to install, and can you please try it with the verbose (`-v`) option to get more output?

**Comment by amuzychka** [comment]
@blink1073 

I tried it today (to install tifffile without version) and this is what I get:
command: **pip install -v tifffile**
OS:
Distributor ID: AmazonAMI
Description:    Amazon Linux AMI release 2016.09
Release:        2016.09
Kernel version: 4.4.23-31.54.amzn1.x86_64

Here is traceback:
```
Downloading tifffile-0.13.5.tar.gz (93kB)
  Downloading from URL https://pypi.python.org/packages/3a/8f/14e0fbc18d375d7df5a658ad7ac8d336523924ab9afd8c00b87c3941ec66/tifffile-0.13.5.tar.gz#md5=25ce6e373e8d58ac9d5b64e5189e1b31 (from https://pypi.python.org/simple/tifffile/)
    100% |████████████████████████████████| 94kB 3.6MB/s 
  Running setup.py (path:/mnt/tmp/pip-build-HAcaEI/tifffile/setup.py) egg_info for package tifffile
    Running command python setup.py egg_info
    Complete output from command python setup.py egg_info:
    error in tifffile setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
    Cleaning up...
    Command "python setup.py egg_info" failed with error code 1 in /mnt/tmp/pip-build-HAcaEI/tifffile
    Exception information:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 246, in main
        status = self.run(options, args)
      File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
        requirement_set.prepare_files(finder)
      File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 345, in prepare_files
        functools.partial(self._prepare_file, finder))
      File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 290, in _walk_req_to_install
        more_reqs = handler(req_to_install)
      File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 502, in _prepare_file
        abstract_dist.prep_for_dist()
      File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 123, in prep_for_dist
        self.req_to_install.run_egg_info()
      File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 411, in run_egg_info
        command_desc='python setup.py egg_info')
      File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 733, in call_subprocess
        % (command_desc, proc.returncode, cwd))
    InstallationError: Command "python setup.py egg_info" failed with error code 1 in /mnt/tmp/pip-build-HAcaEI/tifffile
```

P.S. For 0.13.4 message the same

**Comment by amuzychka** [comment]
Perhaps it is some environment issue on related AMI
Anyway, using 0.12.x is ok for me.

**Comment by blink1073** [comment]
Ah, I think the problem is an older version of pip on AMI, which does not recognize newer version specifiers.
